### ISSUE TITLE
method_STAGATE

### ISSUE THREAD

**Issue by niklasmueboe** [SpatialHackathon/SpaceHack2023#1]
**Update metadata:**
https://docs.google.com/spreadsheets/d/1QCeAF4yQG4bhZSGPQwwVBj_XF7ADY_2mK5xivAIfHsc/edit#gid=0

**Details of method (publication, GitHub):**
- https://www.nature.com/articles/s41467-022-29439-6
- https://github.com/zhanglabtools/STAGATE

**Comment by peicai** [comment]
Hi, thanks for testing this. For our pipeline, I suppose we would use parameters from the config file if such files are provided for this method.

The config file is marked as optional because not all methods provide config files, but if there are configs available, we should use them.
