### ISSUE TITLE
data_stereoseq_mouse_embryo

### ISSUE THREAD

**Issue by Qirongmao97** [SpatialHackathon/SpaceHack2023#162]
Link: https://db.cngb.org/stomics/datasets/STDS0000058

**Comment by Jieran-S** [comment]
Same here as the other dataset! I created row 31 for this dataset. Would appreciate it if you could kindly update the [metadata](https://docs.google.com/spreadsheets/d/1QCeAF4yQG4bhZSGPQwwVBj_XF7ADY_2mK5xivAIfHsc/edit?usp=sharing) and your progress! Thanks a lot!! :))
