### ISSUE TITLE
SpiceMix annData

### ISSUE THREAD

**Issue by Jieran-S** [SpatialHackathon/SpaceHack2023#210]
## Bug:

https://github.com/SpatialHackathon/SpaceHack2023/blob/2e81727c99ddd5171d403915834d1474820384d2/method/SpiceMix/SpiceMix.py#L98-L118

## Background:

SpiceMix has a highly customized annData function, which frequently leads to snakemake crash.

In [`SpiceMix_optargs.json`](https://github.com/SpatialHackathon/SpaceHack2023/blob/main/method/SpiceMix/SpiceMix_optargs.json), (below), `neighbor=false`, which leads to error at line 98(see above): `args.neighbors not found`.

https://github.com/SpatialHackathon/SpaceHack2023/blob/2e81727c99ddd5171d403915834d1474820384d2/method/SpiceMix/SpiceMix_optargs.json#L1-L7

Also, in SpiceMix [config_1.json](https://github.com/SpatialHackathon/SpaceHack2023/blob/main/method/SpiceMix/config/config_1.json), we defined a `preprocess` parameter so `if preprocess_parameters` can be True (line 111). Since we already define the `optargs` as above, should we remove the `preprocess_parameters` check and directly proceed to SpiceMix customized preprocessing?

@shdam You might be familiar with it. What's ur take?

**Comment by shdam** [comment]
It seems to be some hiccups in the config and optargs. I will add a fix in the update_args branch.
