### ISSUE TITLE
method_DeepST

### ISSUE THREAD

**Issue by naveedishaque** [SpatialHackathon/SpaceHack2023#22]
**Update metadata:**
https://docs.google.com/spreadsheets/d/1QCeAF4yQG4bhZSGPQwwVBj_XF7ADY_2mK5xivAIfHsc/edit#gid=0

**Details of method (publication, GitHub):**
https://academic.oup.com/nar/article/50/22/e131/6761985
https://github.com/JiangBioLab/DeepST

**Comment by Jieran-S** [comment]
Hey @Divya1205 r u still working on this method? If not I can carry on implementing it

**Comment by Divya1205** [comment]
Sure, go ahead. I am working on another method right now.

**Comment by Jieran-S** [comment]
Some updates on this method: 
1. Based on our framework, the data augmentation process, based on their pre-trained DNN on the H&E image cannot be implemented, it could be possible that the performance can be compromised. But we can add this augmentation as an option in our preprocessing phase.
2. The model is a DNN model and it takes quite a long time to run even for our small test dataset (4226 × 2593) the algorithm takes 8 minutes to train, that's without the data augmentation step mentioned in step 1.
