### ISSUE TITLE
Seuart config 5

### ISSUE THREAD

**Issue by Jieran-S** [SpatialHackathon/SpaceHack2023#229]
When running our seurat implementation on config_5 (see below) 

https://github.com/SpatialHackathon/SpaceHack2023/blob/57c47102da861408f946d00ab9b611a2a77eced4/method/seurat/config/config_5.json#L1-L5

The algorithm returns the error of 
```
Error in py_module_import(module, convert = convert) : 
  ModuleNotFoundError: No module named 'pandas'
Run `reticulate::py_last_error()` for details.
Calls: tunek ... leiden -> leiden.matrix -> import -> py_module_import
In addition: There were 12 warnings (use warnings() to see them)
Execution halted
```
Maybe we need to modify the seurat yml?

**Comment by shdam** [comment]
Hmm, it appears I missed opening a PR with my last update to Seurat - main is outdated, and config 5 should no longer exist.

**Comment by shdam** [comment]
I'm confused. 
The branches are different, but it says they are the same...
<img width="1095" alt="image" src="https://github.com/SpatialHackathon/SpaceHack2023/assets/49019552/f8bf639f-22bc-4210-a609-331f1f105826">

**Comment by Jieran-S** [comment]
I think it's cuz u accidentally added them back in another commit? (check the seurat config 5) https://github.com/SpatialHackathon/SpaceHack2023/commit/a256a634ec626ba96d1a48a8b132aab206c6d672 

If it's the only change I can push it via other branch? :)

**Comment by shdam** [comment]
I'll change it to use binary search as well.
