### ISSUE TITLE
method_SCAN-IT

### ISSUE THREAD

**Issue by naveedishaque** [SpatialHackathon/SpaceHack2023#23]
**Update metadata:**
https://docs.google.com/spreadsheets/d/1QCeAF4yQG4bhZSGPQwwVBj_XF7ADY_2mK5xivAIfHsc/edit#gid=0

**Details of method (publication, GitHub):**
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9552951/
https://github.com/zcang/SCAN-IT

**Comment by Jieran-S** [comment]
Hi @zsfrbkv, thank you for implementing the SCAN-IT method. I am checking their source code and wonder if we could add some configurations. For instance:
1. [`model` option for `scanit.tl.spatial_representation` can be `dgi` and `gae`](https://github.com/zcang/SCAN-IT/blob/ebf38949eea9348cd1791f392789a8a8c0ae1e47/scanit/tools/_scanit_representation.py#L98)
2. [`method` option for `scanit.tl.spatial_graph` can be "alpha shape" or "knn"](https://github.com/zcang/SCAN-IT/blob/ebf38949eea9348cd1791f392789a8a8c0ae1e47/scanit/tools/_scanit_representation.py#L29C1-L29C26)
3. [`alpha_n_layer` can be 1 to 3](https://github.com/zcang/SCAN-IT/blob/ebf38949eea9348cd1791f392789a8a8c0ae1e47/scanit/_utils/_alpha.py#L36)
4. Leiden clustering use `res` parameter but we have[ implemented a grid search function](https://github.com/SpatialHackathon/SpaceHack2023/blob/0dc192753f7dd3840afd749e3af48e3d9258cd78/method/SEDR/SEDR_method.py#L99) for converting `res` into cluster number. 

I'm thinking of implementing the aforementioned options to our current script. But I want to ask about your opinions on those changes first as you're more familiar with the model. Do you think those changes make sense?
