### ISSUE TITLE
MERINGUE environment crash (igraph)

### ISSUE THREAD

**Issue by Jieran-S** [SpatialHackathon/SpaceHack2023#239]
```
ERROR: dependency ‘igraph’ is not available for package ‘MERINGUE’
* removing ‘/home/jovyan/conda_envs/meringue_env/lib/R/library/MERINGUE’
Warning messages:
1: In i.p(...) : installation of package ‘igraph’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘/tmp/RtmpMycTCh/file452f27de88a34/MERINGUE_1.0.tar.gz’ had non-zero exit status
```

@shdam

**Comment by Jieran-S** [comment]
Hi, I added 
```
  - r-igraph=1.5.1
```
to `meringue.yml` and the method is runnable (results not guaranteed tho). Could be a fix?

**Comment by szhorvat** [comment]
> Could be a fix?

Did you read igraph's installation instructions, and make sure to follow them carefully?

https://github.com/igraph/rigraph/?tab=readme-ov-file#installation

**Comment by Jieran-S** [comment]
Hi, I read them but can't find a recipe to install via conda/bioconda. The only thing I can find is the [intro on conda website.](https://anaconda.org/r/r-igraph) So I installed it by adding igraph specifically to the env yml file. Do you have any suggestion on installation via conda?

**Comment by szhorvat** [comment]
If you prefer to use conda, I suggest installing the latest igraph version that's available on conda-forge. That's version 2.0.2 for all platforms except Windows, which is lagging behind at 1.6.0. https://anaconda.org/conda-forge/r-igraph

Is there any reason you want to stay with the old 1.5.1 and miss out on bugfixes?

**Comment by Jieran-S** [comment]
Aha good point! No particular reason just as I found version 1.5.1 on the conda website. 

Updated to igraph=2.0.2 and tested. Meringue is now working. I will start a PR about this.
