### ISSUE TITLE
Maple will not work in our benchmarking setting

### ISSUE THREAD

**Issue by Jieran-S** [SpatialHackathon/SpaceHack2023#320]
Hi, 

Maple is a model that requires **Multi-sample** dataset input to generate labels for individual samples (see [publication (esp Fig. 1)](https://www.biorxiv.org/content/10.1101/2022.02.28.482296v2.full) and the code snippet below), whereas in our cases we input individual samples from a dataset. This method might not work under our framework.

The code from their `fit_maple` [function](https://github.com/carter-allen/maple/blob/b173e89a7bc82c6ae09c7e0709d09ed22082172d/R/fit_maple.R#L126-L131):
```
  if(is.null(covars))
  {
    print("Note, no supplied covariates. Will use orig.ident as sample indicator.")
    sample <- as.factor(meta[,"orig.ident"])
    W <- as.matrix(stats::model.matrix(~ sample))
    rownames(W) <- rownames(meta)
```

Whenever I run it within our system, it returns an error as generally our `orig.ident` has only one level for each sample we input. 

error message:
```
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'as.matrix': contrasts can be applied only to factors with 2 or more levels
```

@shdam Could you check if this is the case or any workaround? I can put Maple as a low-priority implementation for now.

**Comment by shdam** [comment]
Hmm, I thought it would work anyway since the single-sample tests went well..
Oh well, it is built on [spruce](https://github.com/carter-allen/spruce/), which may then be the actual method that should be implemented, as that is for single samples.

**Comment by shdam** [comment]
I just saw that spruce is no longer maintained, so perhaps we should exclude maple as well, as it uses spruce.

**Comment by Jieran-S** [comment]
If it can work without error, I'd be happy to include the method. But I keep on getting the aforementioned error message. Did you have the same experience? Do you think there's any workaround?

**Comment by Jieran-S** [comment]
Aha I see! Thanks for the suggestion. I will try to run it after the modification.

We should also dicuss a bit whether to keep the method in the next meeting, given that it's no longer maintained.

**Comment by shdam** [comment]
Yeah, it's unfortunate since it seemed like a decent method, but the P.I. behind it now works in industry.
I am curious to hear how it performs :)

**Comment by Jieran-S** [comment]
Changed to spruce and it seems to work. Close the issue for now
