### ISSUE TITLE
data_visium_breast_cancer_SEDR

### ISSUE THREAD

**Issue by naveedishaque** [SpatialHackathon/SpaceHack2023#41]
**Update metadata:**
https://docs.google.com/spreadsheets/d/1QCeAF4yQG4bhZSGPQwwVBj_XF7ADY_2mK5xivAIfHsc/edit#gid=1453488771

**Details of data(publication, GitHub):**
https://www.10xgenomics.com/resources/datasets/human-breast-cancer-block-a-section-1-1-standard-1-1-0
Processed: [https://github.com/JinmiaoChenLab/SEDR_analyses/tree/master/data/BRCA1](https://github.com/JinmiaoChenLab/SEDR_analyses/)

**Comment by pakiessling** [comment]
@shwong-tw you still working on this or should I implement this?

**Comment by shwong-tw** [comment]
Hi @pakiessling ,

I've finished downloading the raw data to `/home/jovyan/scratch/SpaceHack2/raw_data/visium_breast_cancer_SEDR`
Cannot guarantee this data can be finished before the end of the Hackathon, but will be able to complete this task next week.
If we'd prefer to have this done before the final reporting (which make perfect sense), please feel free to take over this task :) Thank you very much!

**Comment by pakiessling** [comment]
@shwong-tw  Cool I went ahead and implemented it :)

**Comment by Jieran-S** [comment]
hi @pakiessling I'm checking the results in the [google sheet](https://docs.google.com/spreadsheets/d/1QCeAF4yQG4bhZSGPQwwVBj_XF7ADY_2mK5xivAIfHsc/edit?usp=sharing). --Did you update this dataset to the metadata? 
It should be the row with `Visium` in `technology` and `Breast Cancer` in `Tissue` as `in_progress` atm and filled in some columns while I can. Can you check and update those information? Thanks a lot
