### ISSUE TITLE
data_slideseqv2_olfactory_bulb

### ISSUE THREAD

**Issue by naveedishaque** [SpatialHackathon/SpaceHack2023#46]
**Update metadata:**
https://docs.google.com/spreadsheets/d/1QCeAF4yQG4bhZSGPQwwVBj_XF7ADY_2mK5xivAIfHsc/edit#gid=1453488771

**Details of data(publication, GitHub):**
https://singlecell.broadinstitute.org/single_cell/study/SCP815/highly-sensitive-spatial-transcriptomics-at-near-cellular-resolution-with-slide-seqv2#study-summary
Processed: https://stagate.readthedocs.io/en/latest/T3_Slide-seqV2.html

**Comment by pakiessling** [comment]
https://www.nature.com/articles/s41593-022-01030-8

This paper also does Slideseq of olfactory bulb and actually has GT available
