### ISSUE TITLE
data_stereoseq_olfactorybulb_STAGATE

### ISSUE THREAD

**Issue by naveedishaque** [SpatialHackathon/SpaceHack2023#47]
**Update metadata:**
https://docs.google.com/spreadsheets/d/1QCeAF4yQG4bhZSGPQwwVBj_XF7ADY_2mK5xivAIfHsc/edit#gid=1453488771

**Details of data(publication, GitHub):**
https://db.cngb.org/stomics/mosta
Processed: https://stagate.readthedocs.io/en/latest/T4_Stereo.html

**Comment by Jieran-S** [comment]
Seems like already been implemented in issue #165 ? Should I close it?

**Comment by pakiessling** [comment]
#166 pulls from "https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000058/stomics/Mouse_olfa_S1.h5ad",
"https://ftp.cngb.org/pub/SciRAID/stomics/STDS0000058/stomics/Mouse_olfa_S2.h5ad

So this can be closed
