### ISSUE TITLE
method_CellCharter

### ISSUE THREAD

**Issue by naveedishaque** [SpatialHackathon/SpaceHack2023#7]
**Update metadata:**
https://docs.google.com/spreadsheets/d/1QCeAF4yQG4bhZSGPQwwVBj_XF7ADY_2mK5xivAIfHsc/edit#gid=0

**Details of method (publication, GitHub):**
https://www.biorxiv.org/content/10.1101/2023.01.10.523386v1
https://github.com/CSOgroup/cellcharter

**Comment by marcovarrone** [comment]
Hi @Jieran-S, absolutely! 
Feel free to write me for any question :)
