### ISSUE TITLE
metric_Sørensen–Dice_coefficient

### ISSUE THREAD

**Issue by naveedishaque** [SpatialHackathon/SpaceHack2023#73]
**Update metadata:**
https://docs.google.com/spreadsheets/d/1QCeAF4yQG4bhZSGPQwwVBj_XF7ADY_2mK5xivAIfHsc/edit#gid=4776337

**Details of metric (publication, GitHub):**
closely related to Jaccard

**Comment by Jieran-S** [comment]
Same as F1
