### ISSUE TITLE
upload_Visium_DLPFC_data_to_BioImage_Archive

### ISSUE THREAD

**Issue by naveedishaque** [SpatialHackathon/SpaceHack2023#90]
The BioImage Archive should be the de facto home for archiving spatial transcriptomics data. We have permission to upload the LIBD DLPFC dataset to The BioImage Archive.

Please also consult Teresa Zulueta @tzulueta from the BioImage Archive team :)

**Comment by pakiessling** [comment]
Uploaded it here: https://www.ebi.ac.uk/biostudies/bioimages/studies/S-BIAD986

Does it look ok to you @naveedishaque @niklasmueboe ?

**Comment by tzulueta** [comment]
Hi @pakiessling, first of all thanks for the submission, it looks fantastic and super complete! I have two suggestions:

1) You and anyone else that contributed to the submission should be acknowledged in the author list as curator/submitted, you did an enormous job.
2) If you tell me what files correspond to annotations (e.g. segmentation masks), I can help create an annotation section for the submission (like the segmentation masks section here: https://www.ebi.ac.uk/biostudies/bioimages/studies/S-BIAD634). 

I will email you to explain how we can do these things in more detail :)

**Comment by pakiessling** [comment]
Thanks Teresa :)
